sudo: required
services:
    - docker

before_install:
    - docker build -t sharibzafar4/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true sharibzafar4/react-test npm test -- --coverage

after_success:
    - docker build -t sharibzafar4/multi-client ./client
    - docker build -t sharibzafar4/multi-nginx ./nginx
    - docker build -t sharibzafar4/multi-server ./server
    - docker build -t sharibzafar4/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push to docker hub
    - docker push sharibzafar4/multi-client
    - docker push sharibzafar4/multi-nginx
    - docker push sharibzafar4/multi-server
    - docker push sharibzafar4/multi-worker

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "multi-docker-prod"
    env: "MultiDockerProd-env"
    bucket_name: "elasticbeanstalk-us-east-1-183236966505"
    bucket_path: "docker-multi-prod"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_ACCESS_KEY"
